isdebug: 0
# # nci
# metric_files: [
#   # trained/rna2protein_nci60.002/out/metrics.txt,
#   trained/rna2protein_nci60.ResNet34V2.001/out/metrics.txt,
#   # trained/rna2protein_nci60.ResNet50V2.001/out/metrics.txt,
# ]
# tissue29
metric_files: [
  # trained/rna2protein_expression_regressor.033/out/metrics.txt,
  # trained/rna2protein_tissue29.ResNet34V2.001/out/metrics.txt,
  # trained/rna2protein_tissue29.ResNet50V2.001/out/metrics.txt,
  /home/ilpech/repositories/mole.001/trained/cohorts/rna2protein_tissue29.ResNet50V2.c001/rna2protein_tissue29.ResNet50V2.c001.003/out/2023.11.23.10.25.53/rna2protein_tissue29.ResNet50V2.c001.003_0002.val_metrics.txt
]
select_genes: False
changeNegativeProts2Zero: False
use_norm: True
use_half: 0
writeCSV: True
drawDatasetsGT2predictedHeatmap: False
drawDatasetsViolin: False
only_val_by_net_config: False
drawGenesGT2predictedViolin: False