# use false to disable setting
cohortsToTrain:
# here any cohort name 
  rna2protein_nci60.ResNet34V2.mole_c002:
    baseConfigPath: config/gene_expression/train.yaml
    cohortParamsDir: trained/cohorts
    crossValidation:
      # stableValidationPercent: 10
      stableValidationPercent: False
      stableValidationFromConfig: bio_dl/testdata/tissue29_nci60_stable_val.json
      modelsInCohort: 5
    # use minEpochsToFinish = 0 to disable stop after n epoch 
    minEpochsToFinish: 2

  