# use false to disable setting
data:
  # cashPath: bio_dl/cash/dataloader_23
  cashPath: /home/ilpech/repositories/machine_learning/bio_dl/cash/dataloader_23
  # cashPath: /home/gerzog/repositories/machine_learning/bio_dl/cash/dataloader_23
  apiUniprotOutDir: /home/gerzog/repositories/machine_learning/bio_dl/testdata/api_out
  datasets2use:
    # ===== BOTH
    # tissue29: True
    # nci60: True
    # ===== TISSUE29
    # tissue29: True
    # nci60: False
    # ===== NCI60
    tissue29: False
    nci60: True
  # if maxGenesFromDataset == 0 load full dataset
  maxGenesFromDataset: 0
  # tissue29_rna: ./bio_dl/testdata/tissue29.1k_rna.tsv
  # tissue29_prot: ./bio_dl/testdata/tissue29.1k_prot.tsv
  tissue29_rna: ./bio_dl/testdata/tissue29_rna.tsv
  tissue29_prot: ./bio_dl/testdata/tissue29_prot.tsv
  # tissue29_rna: ./bio_dl/testdata/tissue29.005k_rna.tsv
  # tissue29_prot: ./bio_dl/testdata/tissue29.005k_prot.tsv
  nci60_rna: ./bio_dl/testdata/nci60_rna.tsv
  nci60_prot: ./bio_dl/testdata/nci60_prot.tsv
  geneMapping: /home/gerzog/repositories/machine_learning/bio_dl/testdata/human_ids_mapping_2023_08_30.tab
  engs2uniprot_file: /home/gerzog/repositories/machine_learning/bio_dl/testdata/mapping_out/engs2uniprot_human_2023_08_30.txt
  splitGeneFromModelConfig: ./bio_dl/testdata/prot_abundance_regressor.full_tissue29_.2_val_config_NONORM.json
  # splitGeneFromModelConfig: False
  # ifSplitPercentToTrain: 0.72
  ifSplitPercentToTrain: False
  useZeroProt: False
  useNonZeroProt: True
train:
  params_dir: ./trained
  max_var_layer: 1024
  gpus2use: 1
  each_train_has_own_dataset: False
  # net_name: rna2protein_tissue20.ResNet34V2.015
  net_name: rna2protein_nci60.BioPerceptron.001
  finetune_net_name: rna2protein_nci60.ResNet34V2.013_old9ch
  finetune_params_dir: /home/ilpech/repositories/mole.001/trained
  use_finetune_experiments: False
  use_finetune_databases: False
  epoch_start_from: 2
  epochs: 900
  log_interval: 3
  # metric_flush_interval: 500
  metric_flush_interval: 50
  wd: 0.0001
  momentum: 0.9

  optimizer: sgd
  lr:
    mode: [
      # byHand,
      # byPlateu,
      cosineWarmup
    ]
    metric2use: [
      norm_p2_val,
      # denorm_p2_val,
    ]
    byHand:
      0: 0.03
      1: 0.01
      3: 0.003
      5: 0.001
      7: 0.0003
    byPlateu:
      mode: max
      start_value: 0.03
      factor: 0.3
      # number of epochs with no improvement 
      # after which learning rate will be reduced
      patience: 1
      threshold: 0.05
      # number of epochs to wait before 
      # resuming normal operation after lr has been reduced
      cooldown: 2
      min_lr: 0.000001 
    # cosineWarmup:
    #   max_lr: 0.0003
    #   min_lr: 0.0000001 
    #   warmup_steps: 125
    #   first_cycle_steps: 250
    #   step_each_batch: 1
    #   cycle_mult: 1.2
    #   # decrease max learning rate by cycle
    #   gamma: 0.99
    cosineWarmup:
      max_lr: 0.0003
      min_lr: 0.0000001 
      warmup_steps: 250
      first_cycle_steps: 500
      step_each_batch: 1
      cycle_mult: 1.0
      # decrease max learning rate by cycle
      # gamma: 0.8
      gamma: 0.95
      
  batch_size:
    0: 1000
  augm:
    isEnabled: True
    epoch_p:
      0: 0.99
      10: 0.8
model:
    model2use: [
      # wideResNet,
      # ResNetV2,
      BioPerceptron
    ]
    wideResNet:
      num_layers: 34
      width_factor: 3
    ResNetV2:
      num_layers: 34
      width_factor: 1
    # ResNetV2:
    #   num_layers: 50
    #   width_factor: 1
    BioPerceptron:
      input_features_hidden_size: 40 
      hidden_size: 80
      annotations_dropout: 0.25
      hidden_dropout: 0.5



  
