# use false to disable setting
data:
  cashPath: ./bio_dl/cash/dataloader
  datasets2use:
    tissue29: True
    tissue13: False
    nci60: False
  # tissue29_rna: ./bio_dl/testdata/tissue29.005k_rna.tsv
  # tissue29_prot: ./bio_dl/testdata/tissue29.005k_prot.tsv
  # tissue29_rna: ./bio_dl/testdata/tissue29.1k_rna.tsv
  # tissue29_prot: ./bio_dl/testdata/tissue29.1k_prot.tsv
  # tissue29_rna: ./bio_dl/testdata/tissue29.5k_rna.tsv
  # tissue29_prot: ./bio_dl/testdata/tissue29.5k_prot.tsv
  tissue29_rna: ./bio_dl/testdata/tissue29_rna.tsv
  tissue29_prot: ./bio_dl/testdata/tissue29_prot.tsv
  geneMapping: ./bio_dl/testdata/human_18chr_tissue29_ids_mapping.tab
  engs2uniprot_file: ./bio_dl/testdata/mapping_out/engs2uniprot.txt
  genome_mappping_path: ./bio_dl/testdata/human_18chr_tissue29_ids_mapping.tab
  skipMissing: False
  # splitGeneFromModelConfig: ./bio_dl/testdata/prot_abundance_regressor.full_tissue29_.2_val_config.json
  splitGeneFromModelConfig: ./bio_dl/testdata/prot_abundance_regressor.full_tissue29_.2_val_config_NONORM.json
  # splitGeneFromModelConfig: False
  # ifSplitPercentToTrain: 0.8 
  ifSplitPercentToTrain: False
  useZeroProt: False
  useNonZeroProt: True
train:
  params_dir: ./trained
  max_var_layer: 2048
  gpus2use: 1
  each_train_has_own_dataset: False
  net_name: rna2protein_expression_regressor.030
  finetune_net_name: prot_abundance_regressor.029
  finetune_params_dir: /home/ilpech/repositories/machine_learning/trained
  epoch_start_from: 5
  epochs: 900
  log_interval: 3
  wd: 0.0001
  momentum: 0.9
  optimizer: sgd
  lr:
    0: 0.003
    # 3: 0.03
    # 5: 0.1
    # 7: 0.01
    # 5: 0.01
    # 5: 0.001
    # 15: 0.005
    # 10: 0.0008
    # 3: 0.01
    # 5: 0.0005
    # 12: 0.0001
    # 100: 0.001
  batch_size:
    # 0: 256
    # 5: 128
    # 7: 64
    0: 80
    # 8: 32
    # 60: 64
  augm:
    isEnabled: True
    epoch_p:
      0: 0.99
      10: 0.8
model:
    num_layers: 34
    width_factor: 3

  
