# use false to disable setting
data:
  cashPath: ./bio_dl/cash/dataloader
  datasets2use:
    tissue29: False
    tissue13: False
    nci60: True

  tissue29_rna: ./bio_dl/testdata/tissue29_rna.tsv
  tissue29_prot: ./bio_dl/testdata/tissue29_prot.tsv
  tissue13_rna: ./bio_dl/testdata/tissue13_rna.tsv
  tissue13_prot: ./bio_dl/testdata/tissue13_prot.tsv
  nci60_rna: ./bio_dl/testdata/nci60_rna.tsv
  nci60_prot: ./bio_dl/testdata/nci60_prot.tsv
  geneMapping: ./bio_dl/testdata/human_ids_mapping.tab
  engs2uniprot_file: ./bio_dl/testdata/mapping_out/engs2uniprot_human.txt
  skipMissing: False
  # splitGeneFromModelConfig: ./bio_dl/testdata/prot_abundance_regressor.full_tissue29_.2_val_config.json
  splitGeneFromModelConfig: ./bio_dl/testdata/prot_abundance_regressor.full_tissue29_.2_val_config_NONORM.json
  # splitGeneFromModelConfig: False
  # ifSplitPercentToTrain: 0.8 
  # ifSplitPercentToTrain: False
  useZeroProt: False
train:
  params_dir: ./trained
  max_var_layer: 2048
  gpus2use: 2
  each_train_has_own_dataset: False
  net_name: rna2protein_nci60.002
  finetune_net_name: rna2protein_nci60.001
  finetune_params_dir: /home/ilpech/repositories/machine_learning/trained
  epoch_start_from: 6
  epochs: 900
  log_interval: 3
  metric_flush_interval: 500
  # metric_flush_interval: 1
  wd: 0.0001
  momentum: 0.9
  optimizer: sgd
  lr:
    0: 0.0001
    3: 0.00003
  batch_size:
    0: 80
  augm:
    isEnabled: True
    epoch_p:
      0: 0.99
      10: 0.8
model:
    num_layers: 34
    width_factor: 3

  
